// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type OidcUser struct {
	ID           int64
	UserUid      uuid.UUID
	UserSub      string
	ProviderName string
}

type TreeCache struct {
	OwnerUid     uuid.UUID
	UpdatedAt    time.Time
	Cache        []byte
	CacheVersion int64
}

type User struct {
	Uid          uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
	Username     string
	PasswordHash []byte
	Name         sql.NullString
}
